import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";
import Badge from "../components/Badge";
import Table from "../components/Table";

const time = (value) => new Date(value).toLocaleString();
export default function Dashboard() {
  const [data, setData] = useState({ summary: null, logs: [], incidents: [], alerts: [] }); const [error, setError] = useState(""); const [connected, setConnected] = useState(false); const [notice, setNotice] = useState(null); const navigate = useNavigate();
  const load = useCallback(async () => { try { const [summary, logs, incidents, alerts] = await Promise.all([api.get("/dashboard/summary"), api.get("/logs?page_size=10"), api.get("/incidents?page_size=10"), api.get("/alerts?page_size=10")]); setData({summary:summary.data, logs:logs.data.items, incidents:incidents.data.items, alerts:alerts.data.items}); setError(""); } catch (e) { setError(e.response?.data?.detail || "Unable to load live data."); } }, []);
  useEffect(() => { load(); const base = import.meta.env.VITE_WS_URL || "ws://localhost:8000/api/v1/ws/alerts"; const socket = new WebSocket(`${base}?token=${encodeURIComponent(localStorage.getItem("sentinel_token"))}`); socket.onopen = () => setConnected(true); socket.onclose = () => setConnected(false); socket.onmessage = ({data: message}) => { const alert = JSON.parse(message); setNotice(alert); setData((prev) => ({...prev, alerts:[alert, ...prev.alerts].slice(0, 10), summary: prev.summary ? {...prev.summary, alerts_24h:prev.summary.alerts_24h + 1, open_incidents:prev.summary.open_incidents + 1} : prev.summary})); load(); }; return () => socket.close(); }, [load]);
  const cards = [["Total logs", data.summary?.total_logs ?? "—"], ["Anomalies", data.summary?.anomalies ?? "—"], ["Open incidents", data.summary?.open_incidents ?? "—"], ["Alerts (24h)", data.summary?.alerts_24h ?? "—"]];
  return <main className="shell"><header><div className="brand"><span>◈</span><h1>SentinelAI</h1></div><div className="header-actions"><span className={connected ? "live" : "offline"}>● {connected ? "Live stream" : "Reconnecting"}</span><button className="secondary" onClick={() => { localStorage.removeItem("sentinel_token"); navigate("/login"); }}>Logout</button></div></header><div className="hero"><div><p className="eyebrow">OPERATIONS CONSOLE</p><h2>Incident intelligence, in real time.</h2><p>Isolation Forest monitors per-service behavior and surfaces unexpected activity.</p></div><button onClick={load}>Refresh data</button></div>{error && <div className="error">{error}</div>}{notice && <div className="notice"><Badge value={notice.severity} /><strong> New incident:</strong> {notice.title}</div>}<section className="stats">{cards.map(([label, value]) => <article key={label}><p>{label}</p><strong>{value}</strong></article>)}</section><Table title="Recent logs" rows={data.logs} columns={[{label:"Level",key:"level",badge:true},{label:"Service",key:"service"},{label:"Message",key:"message"},{label:"Time",key:"timestamp",render:(r)=>time(r.timestamp)}]} /><Table title="Active incidents" rows={data.incidents} empty="No incidents detected — your services look healthy." columns={[{label:"Severity",key:"severity",badge:true},{label:"Service",key:"service"},{label:"Incident",key:"title"},{label:"Status",key:"status",badge:true},{label:"Detected",key:"detected_at",render:(r)=>time(r.detected_at)}]} /><Table title="Alert history" rows={data.alerts} columns={[{label:"Severity",key:"severity",badge:true},{label:"Alert",key:"title"},{label:"Message",key:"message"},{label:"Status",key:"status",badge:true}]} /></main>;
}
